### ISSUE TITLE
Colab not working{Getting FilenotFound Error in output]

### ISSUE THREAD

**Issue by NileshArnaiya** [camenduru/one-shot-talking-face-colab#6]
I'm getting the following error on google colab. Please suggest what to do @camenduru  

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-7-0bf0c4b83396>](https://localhost:8080/#) in <module>
     32 clear_output()
     33 
---> 34 show_video(f"/content/out/{random_int}.mp4")

[<ipython-input-7-0bf0c4b83396>](https://localhost:8080/#) in show_video(video_path, video_width)
      5 
      6 def show_video(video_path, video_width = 256):
----> 7   video_file = open(video_path, "r+b").read()
      8   video_url = f"data:video/mp4;base64,{b64encode(video_file).decode()}"
      9   return HTML(f"""<video width={video_width} controls><source src="{video_url}"></video>""")

FileNotFoundError: [Errno 2] No such file or directory: '/content/out/198233.mp4'`

**Comment by camenduru** [comment]
please use with .wav file

**Comment by NileshArnaiya** [comment]
Silly of me
